# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build
markdown: kramdown

gems: [jekyll-sitemap, jekyll-paginate]

exclude: [vendor]

# Permalinks
permalink: /:title/

# Site
title: Lasha Efremidze

url: http://efremidze.com

author:
    twitter: lasha_
    github: efremidze
    linkedin: efremidze

links:
    github: 'https://github.com/efremidze/efremidze.github.io'
    issue: '%links.github%/issues/new'
    pull: '%links.github%/compare'

paginate: 4

excerpt_separator: <!--excerpt-->
