# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://efremidze.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Lasha Efremidze
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  header_text_feature_image:

  # Icons
  rss: false
  email_address: "efremidzel@gmail.com" # Full email address, e.g. "sam@example.com"
  github: "efremidze"
  instagram: "efremidze"
  linkedin: "https://www.linkedin.com/in/efremidze" # Full URL
  stack_exchange: "http://stackoverflow.com/users/1804731/efremidze" # Full URL
  twitter: "lasha_"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

author:
  name: Lasha Efremidze

# LINKS
links:
  github: 'https://github.com/efremidze/efremidze.github.io'
  issue: 'https://github.com/efremidze/efremidze.github.io/issues/new'
  pull: 'https://github.com/efremidze/efremidze.github.io/compare'

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
